name: CI

# Events that trigger this workflow on push to the main branch or pull request
on:
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest   #this is an ubuntu container where we can test the application

    # Steps in the workflow
    steps:
      #Step 1 : Check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v2
      
      #Step 2 : Set up python environment in the testing container
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
        
      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Step 4 : Run tests
      - name: Run test
        run: pytest


